name: deno-deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: { contents: read, id-token: write }
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with: { deno-version: v1.x }
      - run: deno task fmt --check
      - run: deno task lint
      # - run: deno task test # Uncomment when tests are added
      - uses: denoland/deployctl@v1
        with:
          project: ${{ secrets.DENO_PROJECT }} # Set this secret in GitHub repo settings
          entrypoint: main.ts